Build sp vm (#1)
* sync with sp-kata

* sync with last verion

* test git clone

* echo->cat

* self hosted runner test

* test upload to s3

* checkout current repo

* try to fix latest tag

* added fetching repo with tags

* fix directory to s3 step

* check file existing

* try to fix uploading

* try upload manualy

* fake files

* create json

* fixed json

* rm extra new line

* create release

* fixed json

* provider config

* using runnerid instead of increment tag

* fixed runner id

* fixed tag

* real build

diff --git a/.github/workflows/build-sp-vm.yml b/.github/workflows/build-sp-vm.yml
--- a/.github/workflows/build-sp-vm.yml
+++ b/.github/workflows/build-sp-vm.yml
@@ -1,30 +1,117 @@
-# This is a basic workflow to help you get started with Actions
-
-name: Build SuperProtocol VM
-
-# Controls when the workflow will run
+name: Build SuperProtocol OS image
 on:
-  # Allows you to run this workflow manually from the Actions tab
+  workflow_call:
   workflow_dispatch:
+    inputs:
+      target-branch:
+        required: true
+        type: string
+        description: sp-kata-containers branch
+        default: "sp-main"
+      runs-on:
+        required: true
+        type: choice
+        description: github runner for build
+        options:
+        - sp-vm-runner
+        - ubuntu-latest
 
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
-  # This workflow contains a single job called "build"
-  build:
-    # The type of runner that the job will run on
-    runs-on: ubuntu-latest
+  build-asset:
+    runs-on: ${{ inputs.runs-on }}
+    env:
+      S3_BUCKET: "builds-vm"
+      UPLOAD_FILES: "rootfs.img OVMF.fd root_hash.txt vmlinuz"
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-      - uses: actions/checkout@v4
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
-      # Runs a single command using the runners shell
-      - name: Run a one-line script
-        run: echo Hello, world!
+      - name: Get sp-kata-containers sources
+        uses: actions/checkout@v4
+        with:
+          repository: Super-Protocol/sp-kata-containers
+          path: sp-kata-containers
+          fetch-depth: 0
+          ref: ${{ inputs.target-branch }}
 
-      # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
+      - name: Get sp-kata-containers sources
+        uses: actions/checkout@v4
+        with:
+          repository: Super-Protocol/sp-kata-containers
+          path: sp-kata-containers
+          fetch-depth: 0
+          ref: ${{ inputs.target-branch }}
+
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Build
+        working-directory: sp-kata-containers
         run: |
-          echo Add other actions to build,
-          echo test, and deploy your project.
+          sudo apt-get update
+          sudo apt-get -y install curl s3cmd
+          sudo bash ./sp-build.sh /sp
+
+      - name: Set TAG variable
+        run: echo "TAG=build-${{ github.run_number }}" >> $GITHUB_ENV
+
+      - name: Upload files to s3
+        working-directory: sp-kata-containers/build
+        run: |
+          s3cmd --access_key=${{ secrets.S3_ACCESS_KEY }} \
+                --secret_key=${{ secrets.S3_SECRET_KEY }} \
+                --host=gateway.storjshare.io \
+                --host-bucket="%(bucket)s.gateway.storjshare.io" \
+                put ${UPLOAD_FILES} "s3://${S3_BUCKET}/${TAG}/"
+
+      - name: Create JSON asset
+        working-directory: sp-kata-containers/build
+        run: |
+          IFS=' ' read -r -a FILES <<< "${UPLOAD_FILES}"
+          JSON="{\n"
+
+          for file in "${FILES[@]}"; do
+            if [ -f "$file" ]; then
+              key=$file
+              case $file in
+                rootfs.img) key="rootfs" ;;
+                OVMF.fd) key="bios" ;;
+                root_hash.txt) key="root_hash" ;;
+                vmlinuz) key="kernel" ;;
+              esac
+
+              SHA256=$(sha256sum "$file" | awk '{print $1}')
+              JSON+="  \"${key}\": {\n"
+              JSON+="    \"bucket\": \"${S3_BUCKET}\",\n"
+              JSON+="    \"prefix\": \"${TAG}\",\n"
+              JSON+="    \"filename\": \"$file\",\n"
+              JSON+="    \"sha256\": \"$SHA256\"\n"
+              JSON+="  },\n"
+            else
+              echo "File ${file} not found"
+              exit 1
+            fi
+          done
+
+          JSON="${JSON%,*}"
+          JSON+="\n}"
+          echo -e "$JSON" > vm.json
+
+          echo "JSON successfully created"
+          cat vm.json
+
+      - name: Create Release
+        uses: softprops/action-gh-release@v2
+        with:
+          tag_name: ${{ env.TAG }}
+          release_name: Release ${{ env.TAG }}
+          draft: false
+          prerelease: true
+          files: |
+            sp-kata-containers/build/vm.json
